// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { shellQuote } from "../runner.js";
import type { StateFileRestorePolicy, StateFileRestoreSpec } from "./state-file-restore-policy.js";

const DCODE_AGENT_NAME = "langchain-deepagents-code";
const DCODE_CONFIG_DIR = "/sandbox/.deepagents";
const DCODE_CONFIG_FILE = "config.toml";

/**
 * Deep Agents Code config restore source-of-truth boundary.
 *
 * DCode stores durable user preferences and NemoClaw-generated inference
 * routing in the same TOML file. A wholesale backup restore would replace the
 * newly generated provider/model selection, while dropping the file would lose
 * user-owned settings. Until the agent manifest can express key-level
 * ownership, restore must merge this one canonical file through a local,
 * explicit key allowlist.
 * TODO(#6334): remove this policy when manifests support key-level ownership.
 */
function shouldMergeManagedDcodeConfigStateFile(
  agentType: string | null | undefined,
  dir: string,
  spec: StateFileRestoreSpec,
): boolean {
  return (
    agentType === DCODE_AGENT_NAME &&
    dir.replace(/\/+$/, "") === DCODE_CONFIG_DIR &&
    spec.strategy === "copy" &&
    spec.path === DCODE_CONFIG_FILE
  );
}

/**
 * Runs inside the freshly rebuilt DCode sandbox.
 *
 * The fresh config owns every table. The backup may contribute only validated
 * cosmetic UI and thread-list preferences; routing, credentials, executable
 * behavior, trust expansion, and unknown keys are dropped. Both inputs are
 * parsed before a same-directory staged file atomically replaces the live
 * config. Any detected read, parse, serialization, or target-drift failure
 * leaves the freshly generated file untouched, and atomic replacement avoids
 * exposing partial file contents.
 */
export const DCODE_CONFIG_MERGE_PYTHON = String.raw`
import copy
import os
import stat
import sys
import tomllib
import tomli_w

MAX_CONFIG_BYTES = 16 * 1024 * 1024
GENERATED_HEADER = "# Generated by NemoClaw. This file contains no provider secrets."
PROVIDER_HEADER_PREFIX = "# NemoClaw provider route: "


def fail(message):
    raise SystemExit(message)


def read_regular_file(path, label):
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    try:
        fd = os.open(path, flags)
    except OSError:
        fail(f"{label} DCode config is missing or unsafe")
    try:
        metadata = os.fstat(fd)
        if not stat.S_ISREG(metadata.st_mode) or metadata.st_nlink != 1:
            fail(f"{label} DCode config is not a single regular file")
        if metadata.st_size > MAX_CONFIG_BYTES:
            fail(f"{label} DCode config exceeds the restore size limit")
        chunks = []
        total = 0
        while True:
            chunk = os.read(fd, 65536)
            if not chunk:
                break
            total += len(chunk)
            if total > MAX_CONFIG_BYTES:
                fail(f"{label} DCode config exceeds the restore size limit")
            chunks.append(chunk)
    finally:
        os.close(fd)
    try:
        text = b"".join(chunks).decode("utf-8")
    except UnicodeDecodeError:
        fail(f"{label} DCode config is not valid UTF-8")
    try:
        parsed = tomllib.loads(text)
    except tomllib.TOMLDecodeError:
        fail(f"{label} DCode config is not valid TOML")
    if not isinstance(parsed, dict):
        fail(f"{label} DCode config must be a TOML document")
    return text, parsed, metadata


def fresh_generated_headers(text):
    lines = text.splitlines()
    if len(lines) < 2 or lines[0] != GENERATED_HEADER:
        fail("current DCode config is missing the generated NemoClaw header")
    provider_header = lines[1]
    if not provider_header.startswith(PROVIDER_HEADER_PREFIX):
        fail("current DCode config is missing generated provider metadata")
    if len(provider_header) > 2048 or any(ord(char) < 32 for char in provider_header):
        fail("current DCode config has unsafe generated provider metadata")
    return GENERATED_HEADER + "\n" + provider_header


def assert_fresh_managed_tables(current):
    for table_name in ("models", "update"):
        if not isinstance(current.get(table_name), dict):
            fail(f"current DCode config is missing managed [{table_name}] data")


def safe_ui(backup):
    section = backup.get("ui")
    if not isinstance(section, dict):
        return {}
    result = {}
    for key in ("show_scrollbar", "show_url_open_toast"):
        if isinstance(section.get(key), bool):
            result[key] = section[key]
    return result


def safe_threads(backup):
    section = backup.get("threads")
    if not isinstance(section, dict):
        return {}
    result = {}
    if isinstance(section.get("relative_time"), bool):
        result["relative_time"] = section["relative_time"]
    if section.get("sort_order") in ("updated_at", "created_at"):
        result["sort_order"] = section["sort_order"]
    return result


def merge_safe_preferences(backup, current):
    merged = copy.deepcopy(current)
    safe_tables = {
        "ui": safe_ui(backup),
        "threads": safe_threads(backup),
    }
    for table_name, preferences in safe_tables.items():
        if not preferences:
            continue
        current_table = merged.get(table_name)
        table = copy.deepcopy(current_table) if isinstance(current_table, dict) else {}
        table.update(preferences)
        merged[table_name] = table
    return merged


def render_merged_config(backup, current, headers):
    merged = merge_safe_preferences(backup, current)
    try:
        rendered = tomli_w.dumps(merged)
    except Exception:
        fail("merged DCode config could not be serialized safely")
    if not isinstance(rendered, str):
        fail("merged DCode config serializer returned invalid output")
    payload = (headers + "\n\n" + rendered.rstrip() + "\n").encode("utf-8")
    if len(payload) > MAX_CONFIG_BYTES:
        fail("merged DCode config exceeds the restore size limit")
    return payload


def write_staged_and_replace(staged_path, current_path, current_metadata, payload):
    if os.path.dirname(staged_path) != os.path.dirname(current_path):
        fail("DCode config staging path must share the live config directory")
    flags = os.O_WRONLY | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0)
    try:
        fd = os.open(staged_path, flags)
    except OSError:
        fail("DCode config staging file is missing or unsafe")
    try:
        staged_metadata = os.fstat(fd)
        if not stat.S_ISREG(staged_metadata.st_mode) or staged_metadata.st_nlink != 1:
            fail("DCode config staging file is not a single regular file")
        written = 0
        while written < len(payload):
            written += os.write(fd, payload[written:])
        os.fchmod(fd, 0o660)
        os.fsync(fd)
    finally:
        os.close(fd)

    try:
        latest = os.lstat(current_path)
    except OSError:
        fail("current DCode config changed before atomic restore")
    if stat.S_ISLNK(latest.st_mode) or (
        latest.st_dev,
        latest.st_ino,
    ) != (
        current_metadata.st_dev,
        current_metadata.st_ino,
    ):
        fail("current DCode config changed before atomic restore")

    # The fresh, idle DCode runtime and this restore run as the same sandbox
    # user, which already owns this directory. This check catches accidental
    # target drift; os.replace atomically replaces the directory entry without
    # following a swapped destination symlink. Hostile same-UID writes have the
    # same config authority immediately before and after this operation.
    os.replace(staged_path, current_path)
    directory_fd = os.open(os.path.dirname(current_path), os.O_RDONLY)
    try:
        os.fsync(directory_fd)
    finally:
        os.close(directory_fd)


def main():
    if len(sys.argv) != 4:
        fail("expected backup, current, and staging DCode config paths")
    backup_path, current_path, staged_path = sys.argv[1:]
    _backup_text, backup, _backup_metadata = read_regular_file(backup_path, "backed-up")
    current_text, current, current_metadata = read_regular_file(current_path, "current")
    headers = fresh_generated_headers(current_text)
    assert_fresh_managed_tables(current)
    payload = render_merged_config(backup, current, headers)
    write_staged_and_replace(staged_path, current_path, current_metadata, payload)


main()
`.trim();

/**
 * Build the SSH-side restore command. The backed-up TOML is supplied on stdin.
 */
export function buildDcodeConfigMergeRestoreCommand(dir: string): string {
  const normalizedDir = dir.replace(/\/+$/, "");
  if (normalizedDir !== DCODE_CONFIG_DIR) {
    throw new Error(`DCode config merge requires ${DCODE_CONFIG_DIR}`);
  }
  const destination = shellQuote(`${normalizedDir}/${DCODE_CONFIG_FILE}`);
  return [
    `dst=${destination}`,
    'parent="$(dirname "$dst")"',
    '[ -d "$parent" ] && [ ! -L "$parent" ] || { echo "unsafe DCode config parent" >&2; exit 10; }',
    '[ -f "$dst" ] && [ ! -L "$dst" ] || { echo "fresh DCode config is missing or unsafe" >&2; exit 11; }',
    'backup_tmp="$(mktemp "${parent}/.nemoclaw-dcode-backup.XXXXXX")"',
    'staged_tmp="$(mktemp "${parent}/.nemoclaw-dcode-merged.XXXXXX")"',
    'trap \'rm -f -- "$backup_tmp" "$staged_tmp"\' EXIT',
    'cat > "$backup_tmp"',
    'chmod 600 "$backup_tmp" "$staged_tmp"',
    `/opt/venv/bin/python3 -I -c ${shellQuote(DCODE_CONFIG_MERGE_PYTHON)} "$backup_tmp" "$dst" "$staged_tmp"`,
  ].join("; ");
}

/**
 * Restore capability supplied only for a known stock managed DCode target.
 * Backup provenance and the canonical file boundary are checked again here.
 */
export const managedDcodeConfigRestorePolicy: StateFileRestorePolicy = (
  agentType,
  dir,
  spec,
  backupContents,
) => {
  if (!shouldMergeManagedDcodeConfigStateFile(agentType, dir, spec)) return null;
  return {
    command: buildDcodeConfigMergeRestoreCommand(dir),
    input: backupContents,
  };
};
