// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { parse, stringify } from "smol-toml";
import { loadAgent, type StateFileKeyAllowlistRestoreOwnership } from "../agent/defs";
import { shellQuote } from "../runner";
import {
  buildKeyAllowlistMergeRestoreCommand,
  KEY_ALLOWLIST_MERGE_PYTHON,
  stateFileKeyMergeSpec,
} from "./state-file-key-merge";

export const GENERATED_HEADER = "# Generated by NemoClaw. This file contains no provider secrets.";
export const FRESH_PROVIDER_HEADER =
  "# NemoClaw provider route: inference; upstream provider: compatible-endpoint; API: openai-completions.";

const PYTHON_TEST_TOMLI_WRITER_SHIM = String.raw`
import json
import subprocess
import sys
import types

NODE_TOML_WRITER = r"""
const fs = require("node:fs");
const { stringify } = require("smol-toml");
const value = JSON.parse(fs.readFileSync(0, "utf8"));
process.stdout.write(stringify(value));
"""

def dumps(value):
    completed = subprocess.run(
        ["node", "-e", NODE_TOML_WRITER],
        input=json.dumps(value, allow_nan=False),
        capture_output=True,
        check=True,
        text=True,
    )
    return completed.stdout

tomli_w = types.ModuleType("tomli_w")
tomli_w.dumps = dumps
sys.modules["tomli_w"] = tomli_w

try:
    script_index = sys.argv.index("-c", 1) + 1
except ValueError:
    script_index = 1
script = sys.argv[script_index]
sys.argv = [sys.argv[0], *sys.argv[script_index + 1:]]
exec(script, {"__name__": "__main__"})
`.trim();

export const INODE_SWAP_MARKER = "# replacement created during race test\n";
function failInstrumentation(label: string): never {
  throw new Error(`Could not instrument the ${label}`);
}

function requireInstrumented(instrumented: string, label: string): string {
  return instrumented !== KEY_ALLOWLIST_MERGE_PYTHON ? instrumented : failInstrumentation(label);
}

const INODE_REVALIDATION_POINT = String.raw`        try:
            latest_current = os.stat(current_name, dir_fd=parent_fd, follow_symlinks=False)`;
export const INODE_SWAP_SCRIPT = requireInstrumented(
  KEY_ALLOWLIST_MERGE_PYTHON.replace(
    INODE_REVALIDATION_POINT,
    String.raw`        swapped_name = current_name + ".pre-swap"
        os.replace(current_name, swapped_name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd)
        replacement_fd = os.open(
            current_name,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o660,
            dir_fd=parent_fd,
        )
        try:
            os.write(replacement_fd, b"# replacement created during race test\n")
            os.fsync(replacement_fd)
        finally:
            os.close(replacement_fd)

        try:
            latest_current = os.stat(current_name, dir_fd=parent_fd, follow_symlinks=False)`,
  ),
  "current-config inode revalidation point",
);

export const IN_PLACE_MUTATION_SCRIPT = requireInstrumented(
  KEY_ALLOWLIST_MERGE_PYTHON.replace(
    INODE_REVALIDATION_POINT,
    String.raw`        mutation_fd = os.open(
            current_name,
            os.O_WRONLY | getattr(os, "O_NOFOLLOW", 0),
            dir_fd=parent_fd,
        )
        try:
            os.lseek(mutation_fd, 0, os.SEEK_END)
            os.write(mutation_fd, b"# concurrent mutation\n")
            os.fsync(mutation_fd)
        finally:
            os.close(mutation_fd)

        try:
            latest_current = os.stat(current_name, dir_fd=parent_fd, follow_symlinks=False)`,
  ),
  "current-config version revalidation point",
);

const STAGE_REVALIDATION_POINT = String.raw`        try:
            latest_staged = os.stat(staged_name, dir_fd=parent_fd, follow_symlinks=False)`;

export function stageSwapScript(kind: "hardlink" | "regular" | "symlink"): string {
  const replacement =
    kind === "symlink"
      ? "os.symlink(attack_name, staged_name, dir_fd=parent_fd)"
      : kind === "hardlink"
        ? "os.link(attack_name, staged_name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd, follow_symlinks=False)"
        : String.raw`replacement_fd = os.open(
            staged_name,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o600,
            dir_fd=parent_fd,
        )
        try:
            os.write(replacement_fd, b"replacement stage must not be installed\n")
            os.fsync(replacement_fd)
        finally:
            os.close(replacement_fd)`;
  return requireInstrumented(
    KEY_ALLOWLIST_MERGE_PYTHON.replace(
      STAGE_REVALIDATION_POINT,
      String.raw`        attack_name = ".nemoclaw-stage-attack-target"
        attack_fd = os.open(
            attack_name,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o600,
            dir_fd=parent_fd,
        )
        try:
            os.write(attack_fd, b"stage attack target must remain unchanged\n")
            os.fsync(attack_fd)
        finally:
            os.close(attack_fd)
        os.unlink(staged_name, dir_fd=parent_fd)
        ${replacement}

        try:
            latest_staged = os.stat(staged_name, dir_fd=parent_fd, follow_symlinks=False)`,
    ),
    "staged-config inode revalidation point",
  );
}

function loadDcodeOwnership(): StateFileKeyAllowlistRestoreOwnership {
  const ownership = loadAgent("langchain-deepagents-code").stateFiles.find(
    (stateFile) => stateFile.path === "config.toml",
  )?.restore;
  if (ownership?.merge !== "key-allowlist") {
    throw new Error("Deep Agents config must declare key-allowlist restore ownership");
  }
  return ownership;
}

export const DCODE_OWNERSHIP = loadDcodeOwnership();

export function generatedCurrent(config: unknown, providerHeader = FRESH_PROVIDER_HEADER): string {
  return `${GENERATED_HEADER}\n${providerHeader}\n\n${stringify(config)}`;
}

interface RunMergeOptions {
  script?: string;
}

export function runMergeScript(
  backup: string,
  current: string,
  ownership: StateFileKeyAllowlistRestoreOwnership,
  options: RunMergeOptions = {},
): {
  current: string;
  status: number | null;
  stderr: string;
  stageEntries: string[];
  swappedOriginal: string | null;
} {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nemoclaw-state-file-key-merge-"));
  try {
    const currentPath = path.join(dir, "config.toml");
    fs.writeFileSync(currentPath, current, { mode: 0o660 });

    const result = spawnSync(
      "python3",
      [
        "-I",
        "-c",
        PYTHON_TEST_TOMLI_WRITER_SHIM,
        options.script ?? KEY_ALLOWLIST_MERGE_PYTHON,
        dir,
        "config.toml",
        JSON.stringify(stateFileKeyMergeSpec(ownership)),
      ],
      { encoding: "utf-8", input: backup },
    );
    return {
      current: fs.readFileSync(currentPath, "utf-8"),
      status: result.status,
      stderr: result.stderr,
      stageEntries: fs
        .readdirSync(dir)
        .filter((entry) => entry.startsWith(".nemoclaw-restore-merged.")),
      swappedOriginal: fs.existsSync(`${currentPath}.pre-swap`)
        ? fs.readFileSync(`${currentPath}.pre-swap`, "utf-8")
        : null,
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

interface ProductionRunOptions {
  currentLink?: "hardlink" | "symlink";
  parentAncestorSymlink?: boolean;
  script?: string;
}

function ancestorSymlinkConfigDir(dir: string): { configDir: string; stateFilePath: string } {
  fs.mkdirSync(path.join(dir, "real", "nested"), { recursive: true });
  fs.symlinkSync("real", path.join(dir, "alias"));
  return {
    configDir: path.join(dir, "alias", "nested"),
    stateFilePath: "alias/nested/config.toml",
  };
}

function writePlainCurrentConfig(currentPath: string, current: string): null {
  fs.writeFileSync(currentPath, current, { mode: 0o660 });
  return null;
}

function writeLinkedCurrentConfig(
  dir: string,
  currentPath: string,
  current: string,
  currentLink: "hardlink" | "symlink",
): string {
  const currentTargetPath = path.join(dir, "current.target");
  fs.writeFileSync(currentTargetPath, current, { mode: 0o660 });
  currentLink === "symlink"
    ? fs.symlinkSync(path.basename(currentTargetPath), currentPath)
    : fs.linkSync(currentTargetPath, currentPath);
  return currentTargetPath;
}

export function runProductionCommand(
  backup: string,
  current: string,
  options: ProductionRunOptions = {},
): {
  command: string;
  attackTarget: string | null;
  current: string;
  currentTarget: string | null;
  dir: string;
  entries: string[];
  status: number | null;
  stderr: string;
} {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nemoclaw-state-file-command-"));
  const { configDir, stateFilePath } = options.parentAncestorSymlink
    ? ancestorSymlinkConfigDir(dir)
    : { configDir: dir, stateFilePath: "config.toml" };
  const currentPath = path.join(configDir, "config.toml");
  try {
    const currentTargetPath = options.currentLink
      ? writeLinkedCurrentConfig(dir, currentPath, current, options.currentLink)
      : writePlainCurrentConfig(currentPath, current);
    const baseCommand = buildKeyAllowlistMergeRestoreCommand(
      dir,
      { path: stateFilePath },
      DCODE_OWNERSHIP,
    );
    const commandWithScript = options.script
      ? baseCommand.replace(shellQuote(KEY_ALLOWLIST_MERGE_PYTHON), shellQuote(options.script))
      : baseCommand;
    const command = commandWithScript.replace(
      "/opt/venv/bin/python3",
      `python3 -I -c ${shellQuote(PYTHON_TEST_TOMLI_WRITER_SHIM)}`,
    );
    const result = spawnSync("bash", ["-c", command], {
      encoding: "utf-8",
      input: backup,
    });
    return {
      command,
      attackTarget: fs.existsSync(path.join(dir, ".nemoclaw-stage-attack-target"))
        ? fs.readFileSync(path.join(dir, ".nemoclaw-stage-attack-target"), "utf-8")
        : null,
      current: fs.readFileSync(currentPath, "utf-8"),
      currentTarget: currentTargetPath ? fs.readFileSync(currentTargetPath, "utf-8") : null,
      dir,
      entries: fs.readdirSync(dir),
      status: result.status,
      stderr: result.stderr,
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

export function mergedToml(config: string): Record<string, unknown> {
  return parse(config) as Record<string, unknown>;
}
